# Numpy

In [1]:
import numpy as np

## Creación de arreglos Numpy

In [3]:
mylist = [1,2,3,4,5]
mylist

[1, 2, 3, 4, 5]

In [11]:
np.array(mylist)

array([1, 2, 3, 4, 5])

In [18]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
mymatrix[1][2]

6

In [96]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Algunos métodos básico

In [33]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.linspace(start = 0, stop = 10, num = 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [52]:
np.random.rand(2)

array([0.42239168, 0.9414307 ])

In [53]:
np.random.randn(2)

array([-0.74446084,  0.39636138])

In [55]:
np.random.normal(loc = 0, scale = 3, size = 10)

array([-0.91045796,  1.87291252,  1.38478589,  2.34791663, -4.92207256,
       -1.65901961,  4.04124172,  3.03730888,  0.24390038,  1.12949473])

In [56]:
np.random.randint(1,100)

56

## Algunos atributos y métodos de los arreglos

In [120]:
myarray = np.random.randint(0,50,27)

In [121]:
myarray = myarray.reshape(3,3,3)

In [122]:
print(myarray.max())
print(myarray.min())
print(myarray.argmax())
print(myarray.argmin())

48
3
10
13


In [123]:
myarray.shape

(3, 3, 3)

In [124]:
myarray.dtype

dtype('int64')

In [126]:
myarray[0] = np.array([[2,3,4],[6,5,4],[3,10,3]])

In [127]:
myarray

array([[[ 2,  3,  4],
        [ 6,  5,  4],
        [ 3, 10,  3]],

       [[27, 48,  4],
        [26,  3,  4],
        [19, 25, 41]],

       [[17, 45, 12],
        [ 5, 47,  9],
        [28, 16, 20]]])

In [128]:
myarray2 = myarray

In [129]:
myarray2

array([[[ 2,  3,  4],
        [ 6,  5,  4],
        [ 3, 10,  3]],

       [[27, 48,  4],
        [26,  3,  4],
        [19, 25, 41]],

       [[17, 45, 12],
        [ 5, 47,  9],
        [28, 16, 20]]])

In [130]:
myarray2[0,0,0] = 100

In [131]:
myarray

array([[[100,   3,   4],
        [  6,   5,   4],
        [  3,  10,   3]],

       [[ 27,  48,   4],
        [ 26,   3,   4],
        [ 19,  25,  41]],

       [[ 17,  45,  12],
        [  5,  47,   9],
        [ 28,  16,  20]]])

In [132]:
myarray2 = myarray.copy()

In [135]:
myarray2[0,0,0] = 99999

In [136]:
myarray

array([[[100,   3,   4],
        [  6,   5,   4],
        [  3,  10,   3]],

       [[ 27,  48,   4],
        [ 26,   3,   4],
        [ 19,  25,  41]],

       [[ 17,  45,  12],
        [  5,  47,   9],
        [ 28,  16,  20]]])

In [138]:
myarray[myarray > 10]

array([100,  27,  48,  26,  19,  25,  41,  17,  45,  12,  47,  28,  16,
        20])

## Operaciones y funciones universales

In [150]:
myarray = np.arange(1, 10)

In [151]:
myarray + myarray

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [152]:
myarray * myarray

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [153]:
myarray - myarray

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [154]:
myarray * myarray

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [155]:
myarray/myarray

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [156]:
1/myarray

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [157]:
myarray**3

array([  1,   8,  27,  64, 125, 216, 343, 512, 729])

In [160]:
np.sqrt(myarray)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [161]:
np.exp(myarray)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [162]:
np.max(myarray)

9

In [163]:
np.sin(myarray)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [164]:
np.log(myarray)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])